//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confectionery_factory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Кондитерская_фабрикаEntities1 : DbContext
    {
        public static Кондитерская_фабрикаEntities1 _context;
        public Кондитерская_фабрикаEntities1()
        : base("name=Кондитерская_фабрикаEntities1")
        {
        }
        public static Кондитерская_фабрикаEntities1 GetContext()

        {
            if (_context == null)
                _context = new Кондитерская_фабрикаEntities1();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Затраты> Затраты { get; set; }
        public virtual DbSet<Изделия> Изделия { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Поставки_изделий> Поставки_изделий { get; set; }
        public virtual DbSet<Поставки_сырья> Поставки_сырья { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Сырье> Сырье { get; set; }
    }
}
