//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confectionery_factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставки_сырья
    {
        public int Код_поставки { get; set; }
        public int Код_сырья { get; set; }
        public string ФИО_менеджера { get; set; }
        public Nullable<System.DateTime> Дата_поставки { get; set; }
        public Nullable<decimal> Количество_сырья { get; set; }
        public string Единица_измерения { get; set; }
        public string Организация_поставщика { get; set; }
        public string Телефон_поставщика { get; set; }
    
        public virtual Сырье Сырье { get; set; }
    }
}
