//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confectionery_factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователь
    {
        public int Код { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Код_роли { get; set; }
        public string Имя { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
